[tool.poetry]
name = "hworder"
version = "v1.0.3"
description = "A sample Python project"
authors = [
  "Pavel Mokeev <pav3l.mokeev@gmail.com>"
]
license = "APACHE"
readme = "README.md"
homepage = "https://ya.ru/"
repository = "https://github.com/pmokeev/hello-worlder"
classifiers = [
  "Intended Audience :: Developers",
]

[tool.poetry.dependencies]
python = "^3.10.0"
numpy = "^1.26.4"

[tool.poetry.dev-dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"