[tool.poetry]
name = "qcentroid-agent-cli"
version = "0.3.23"
description = "Library to interact with qcentroid agent api"
authors = [
  "QCentroid <info@qcentroid.xyz>" ]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    ]
license = "MIT License"
readme = "README.md"
packages = [{include = "qcentroid_agent_cli"}]
[project.urls]
Homepage = "https://github.com/QCentroid/qcentroid-agent-api"
Issues = "https://github.com/QCentroid/qcentroid-agent-api/issues"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
