[tool.poetry]
name = "mkconf"
version = "0.2.0"
description = "Plugin for MKDocs to create conference websites"
authors = ["Leandro G. Almeida <leandro.g.almeida@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "mkconf", from = "src"}]


[tool.poetry.plugins."mkdocs.plugins"]
mkconf = "mkconf.plugin:ConfPlugin"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.5.3"
Jinja2 = "^3.1.3"



[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
pytest-cov = "^4.1.0"
pytest-xdist = "^3.5.0"
ruff = "^0.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
