runtime: custom
env: flex
service: {name-your-service}
threadsafe: true

runtime_config:
  jdk: openjdk8
  
resources:
  cpu: 16
  memory_gb: 20

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  target_concurrent_requests: 3
  cpu_utilization:
    target_utilization: 0.5

env_variables:
  SPRING_PROFILES_ACTIVE: production
  DD_TRACE_AGENT_HOSTNAME: 'datadog-proxy.xoominfo.com'
  DD_SERVICE_NAME: '{name-your-service}'
  DD_LOGS_INJECTION: "true"

handlers:
- url: /.*
  script: this field is required, but ignored

network:
  name: default
  subnetwork_name: default
  instance_tag: allow-ssh
