[tool.poetry]
name = "dns-archiver"
version = "0.1.0"
description = "A CLI tool to dump DNS records into an archive"
authors = ["Adam McKay <adam@beepboop.digital>"]
readme = "README.md"
packages = [
    {include = "dns_archiver", from = "src"},
]

[tool.poetry.scripts]
dns-archiver = "dns_archiver.__main__:app"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
typer = "^0.9.0"
rich = "^13.6.0"
dnspython = "^2.6.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
ruff = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["F", "E", "W", "I", "PL"]
ignore = ["E501", "W191"]

[tool.ruff.lint.isort]
known-first-party = ["gronpy"]

[tool.ruff.lint.pylint]
max-returns = 10
max-branches = 20