name: lint & test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install rye
        uses: eifinger/setup-rye@v1

      - name: Load cached venv
        id: cached-venv-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        if: steps.cached-venv-dependencies.outputs.cache-hit != 'true'
        run: |
          rye pin cpython@${{ matrix.python-version }}
          rye sync

      - name: Load cached pre-commit
        id: cached-pre-commit-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: precommit-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Code checks
        run: |
          rye run pre-commit run --all-files --show-diff-on-failure

      - name: Test with pytest
        run: |
          rye run pytest