[tool.poetry]
name = "mainshortcuts"
version = "1.6.62"
description = "Simplifying Python Built-in Commands"
authors = ["MainPlay TG <xbox.roman6666666666@gmail.com>"]
readme = "README.md"
repository = "https://github.com/MainPlay-TG/MainShortcuts.py"
packages = [
    { include = "MainShortcuts", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.scripts]
MS-jsonC = "MainShortcuts.script:jsonCompress"
MS-jsonP = "MainShortcuts.script:jsonPretty"
MS-getCore = "MainShortcuts.script:getCore"
MS-getCoreMini = "MainShortcuts.script:getCoreMini"
MS-mkdir = "MainShortcuts.script:mkdir"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
